// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login.post').default>>>>
    }
    '/api/auth/logout': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/logout.post').default>>>>
    }
    '/api/auth/session': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/session.get').default>>>>
    }
    '/api/incidents/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/incidents/[id].get').default>>>>
    }
    '/api/incidents/:id/analyze': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/incidents/[id]/analyze.post').default>>>>
    }
    '/api/incidents/:id/context': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/incidents/[id]/context.post').default>>>>
    }
    '/api/incidents/:id/simulate': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/incidents/[id]/simulate.post').default>>>>
    }
    '/api/incidents': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/incidents/index.get').default>>>>
    }
    '/api/settings/ai': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/settings/ai.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/settings/ai.post').default>>>>
    }
    '/api/settings/git': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/settings/git.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/settings/git.post').default>>>>
    }
    '/api/settings/sandbox': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/settings/sandbox.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/settings/sandbox.post').default>>>>
    }
    '/api/users/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/[id].delete').default>>>>
    }
    '/api/users': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/index.post').default>>>>
    }
    '/health': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/health.get').default>>>>
    }
    '/v1/events': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/v1/events.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/@nuxt+nitro-server@4.4.8_@babel+plugin-syntax-typescript@7.29.7_@babel+core@7.29.7__db0_bb95d7d22ff523046512a28611d8f7b9/node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}