packages:
  - "apps/*"
  - "packages/*"
  - "packages/providers/*"
  - "examples/*"

onlyBuiltDependencies:
  - esbuild
allowBuilds:
  '@parcel/watcher': set this to true or false
  esbuild: true
  vue-demi: set this to true or false
